// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: ui

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, 10 );
lv_obj_set_y( ui_Label1, 26 );
lv_label_set_text(ui_Label1,"SSID:");

ui_Label2 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, 10 );
lv_obj_set_y( ui_Label2, 10 );
lv_label_set_text(ui_Label2,"Status:");

ui_Label3 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, 10 );
lv_obj_set_y( ui_Label3, 43 );
lv_label_set_text(ui_Label3,"IP:");

ui_status = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_status, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_status, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_status, 62 );
lv_obj_set_y( ui_status, 10 );
lv_label_set_text(ui_status,"-");

ui_ssid = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_ssid, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ssid, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ssid, 50 );
lv_obj_set_y( ui_ssid, 26 );
lv_label_set_text(ui_ssid,"-");

ui_ip = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_ip, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ip, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ip, 30 );
lv_obj_set_y( ui_ip, 42 );
lv_label_set_text(ui_ip,"-");

}
